# Generated by Django - custom migration for field rename

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djust_rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='property',
            new_name='rental_property',
        ),
    ]
