# Generated by Django 4.2.26 on 2025-11-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djust_rentals', '0002_rename_lease_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='rental_property',
            new_name='property',
        ),
    ]
