"""
Template strings for scaffolding new djust projects.

All templates use ``%(variable)s`` substitution to avoid conflicts with
Django template syntax (``{%%}``, ``{{ }}``).
"""

# ---------------------------------------------------------------------------
# manage.py
# ---------------------------------------------------------------------------

MANAGE_PY = """\
#!/usr/bin/env python
\"\"\"Django's command-line utility for administrative tasks.\"\"\"
import os
import sys


def main():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "%(app_name)s.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
"""

# ---------------------------------------------------------------------------
# __init__.py (app package)
# ---------------------------------------------------------------------------

INIT_PY = ""

# ---------------------------------------------------------------------------
# apps.py
# ---------------------------------------------------------------------------

APPS_PY = """\
from django.apps import AppConfig


class %(app_class)sConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "%(app_name)s"
"""

# ---------------------------------------------------------------------------
# settings.py
# ---------------------------------------------------------------------------

SETTINGS_PY = """\
\"\"\"
Django settings for %(app_name)s project.
Generated by ``python -m djust new``.
\"\"\"

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path):
    \"\"\"Load ``KEY=VALUE`` pairs from a ``.env`` file into ``os.environ``.

    Dependency-free (no python-dotenv): values already present in the
    environment win, so real deployments that export real env vars are
    never overridden by a committed ``.env``. Blank lines and ``#``
    comments are skipped.
    \"\"\"
    if not path.exists():
        return
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip())


# Load a ``.env`` next to BASE_DIR (if present) so local development picks up
# ``DEBUG=True`` + a real ``SECRET_KEY`` without exporting them by hand. An
# unconfigured deploy (no ``.env``) still fails safe to ``DEBUG=False``.
_load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-%(secret_key)s",
)  # noqa: S105

# Fails safe: defaults to False when the env var is unset so production
# deployments don't accidentally ship with full tracebacks and lax security.
# Copy ``.env.example`` to ``.env`` for local development.
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

INSTALLED_APPS = [
    "channels",
%(admin_app)s    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "djust",
%(theming_app)s    "%(app_name)s",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "%(app_name)s.urls"

TEMPLATES = [
    {
        "BACKEND": "djust.template_backend.DjustTemplateBackend",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
%(theming_context_processor)s            ],
        },
    },
%(admin_template_backend)s]

ASGI_APPLICATION = "%(app_name)s.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        # Read the DB path the host injects at runtime, falling back to a local
        # file for development. A PaaS app rootfs is typically read-only, so a
        # sqlite file under BASE_DIR would 500 on the first write; hosts such as
        # djustlive mount a writable path and export it as DJUST_SQLITE_PATH.
        "NAME": os.environ.get("DJUST_SQLITE_PATH") or (BASE_DIR / "db.sqlite3"),
    }
}

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LIVEVIEW_ALLOWED_MODULES = [
    "%(app_name)s.views",
]
%(theming_settings)s%(extra_settings)s"""

# ---------------------------------------------------------------------------
# Admin opt-in fragments (only emitted when the project ships models)
# ---------------------------------------------------------------------------
#
# The default in-memory scaffold does NOT install ``django.contrib.admin``:
# the admin has no built-in brute-force protection (djust.A030) and a starter
# LiveView app doesn't need it. When the project actually defines models
# (``--with-db`` / ``--from-schema``), admin is genuinely useful, so these
# fragments are spliced into INSTALLED_APPS / TEMPLATES / urls.py. With admin
# present, A030 fires by design — it's correct guidance to add django-axes
# before exposing /admin/ in production.

# INSTALLED_APPS entry (with trailing newline so it slots cleanly).
ADMIN_APP_ENTRY = '    "django.contrib.admin",\n'

# ``djust.theming`` powers the starter page's theme switcher. Omitted with
# ``--bare``. The context processor is required by djust_theming.E001.
# The shipped presets currently fail their own WCAG contrast check
# (djust_theming.W001; djust-org/djust#2874), so a fresh `manage.py check`
# would print six warnings. Silenced until the presets are fixed.
THEMING_SETTINGS = """\

SILENCED_SYSTEM_CHECKS = ["djust_theming.W001"]
"""
THEMING_APP_ENTRY = '    "djust.theming",\n'
THEMING_CONTEXT_PROCESSOR = '                "djust.theming.context_processors.theme_context",\n'

# Second TEMPLATES backend — django.contrib.admin requires a DjangoTemplates
# backend (admin.E403). APP_DIRS=False so it doesn't shadow app templates
# rendered by djust.
ADMIN_TEMPLATE_BACKEND = """\
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": False,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                "django.template.loaders.app_directories.Loader",
            ],
        },
    },
"""

# urls.py import line + urlpattern entry (each with trailing newline).
ADMIN_URL_IMPORT = "from django.contrib import admin\n"
ADMIN_URL_ENTRY = '    path("admin/", admin.site.urls),\n'

# ---------------------------------------------------------------------------
# asgi.py
# ---------------------------------------------------------------------------

ASGI_PY = """\
\"\"\"
ASGI config for %(project_name)s project.

Wraps the HTTP handler with ``ASGIStaticFilesHandler`` so static files
(client.js, CSS, etc.) are served correctly under an ASGI server like
uvicorn without needing a separate static file server or extra deps.
\"\"\"

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "%(settings_module)s")

# Initialize Django's app registry BEFORE importing anything that touches
# models / consumers (channels, djust.websocket). ``get_asgi_application()``
# calls ``django.setup()`` internally, so the imports below are safe.
django_asgi_app = get_asgi_application()

from django.contrib.staticfiles.handlers import ASGIStaticFilesHandler  # noqa: E402
from django.urls import path  # noqa: E402
from channels.routing import ProtocolTypeRouter, URLRouter  # noqa: E402
from channels.auth import AuthMiddlewareStack  # noqa: E402
from channels.security.websocket import AllowedHostsOriginValidator  # noqa: E402
from djust.websocket import LiveViewConsumer  # noqa: E402

# CSWSH defense: ``AllowedHostsOriginValidator`` rejects WebSocket
# handshakes whose Origin header is not in ``settings.ALLOWED_HOSTS``.
application = ProtocolTypeRouter(
    {
        "http": ASGIStaticFilesHandler(django_asgi_app),
        "websocket": AllowedHostsOriginValidator(
            AuthMiddlewareStack(
                URLRouter(
                    [
                        path("ws/live/", LiveViewConsumer.as_asgi()),
                    ]
                )
            )
        ),
    }
)
"""

# ---------------------------------------------------------------------------
# settings block appended by ``djust init``
# ---------------------------------------------------------------------------
#
# The conditions run inside the user's settings module, so the block is
# correct for list or tuple settings, apps listed by label or AppConfig path,
# and projects that configure their own channel layer, without parsing the
# user's code. TEMPLATES is deliberately untouched: LiveViews read their
# template source directly, and putting DjustTemplateBackend ahead of the
# project's engine breaks the admin's inclusion tags (#2872).

SETTINGS_BLOCK = """\
# --- djust (added by djust init) ---
# Reruns of `djust init` detect this block and leave settings unchanged.
INSTALLED_APPS = [
    *INSTALLED_APPS,
    *[
        app
        for app in ("channels", "djust")
        if not any(entry == app or entry.startswith(app + ".") for entry in INSTALLED_APPS)
    ],
]

ASGI_APPLICATION = "%(asgi_module)s.application"

# In-memory layer: suitable for one local development process.
if "CHANNEL_LAYERS" not in globals():
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
    }
# --- end djust ---
"""

# ---------------------------------------------------------------------------
# wsgi.py
# ---------------------------------------------------------------------------

WSGI_PY = """\
\"\"\"WSGI config for %(app_name)s project.\"\"\"

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "%(app_name)s.settings")

application = get_wsgi_application()
"""

# ---------------------------------------------------------------------------
# urls.py
# ---------------------------------------------------------------------------

URLS_PY = """\
\"\"\"URL configuration for %(app_name)s project.\"\"\"

%(admin_url_import)sfrom django.urls import path

from .views import %(view_class)s

urlpatterns = [
%(admin_url)s    path("", %(view_class)s.as_view(), name="index"),
]
%(extra_urls)s"""

# ---------------------------------------------------------------------------
# views.py — base (no features)
# ---------------------------------------------------------------------------

VIEWS_PY_BASE = """\
\"\"\"LiveView for %(app_name)s.\"\"\"

import djust
from djust import LiveView
from djust.decorators import event_handler
from djust.theming import ThemeMixin
%(extra_imports)s
# Presets offered in the top bar. Any name from djust.theming works here.
DEMO_THEME_PRESETS = ("djust", "catppuccin", "nord", "dracula", "solarized", "rose")

%(extra_data)s
class %(view_class)s(%(view_bases)s):
    template_name = "%(app_name)s/index.html"

    # This starter demo is an in-memory to-do list with no per-user data, so
    # it is intentionally public. ``login_required = False`` acknowledges that
    # explicitly (silences djust.S005). When you add real, user-scoped state,
    # set ``login_required = True`` (or add ``permission_required``) instead.
    login_required = False

    def mount(self, request, **kwargs):
        super().mount(request, **kwargs)
        self.items = [
            {"id": 1, "name": "First item", "done": False},
            {"id": 2, "name": "Second item", "done": False},
            {"id": 3, "name": "Third item", "done": True},
        ]
        self.search_query = ""
        self._next_id = 4
%(extra_mount)s
    def _compute(self):
        \"\"\"Recompute filtered items.\"\"\"
        if self.search_query:
            q = self.search_query.lower()
            self.filtered_items = [
                i for i in self.items if q in i["name"].lower()
            ]
        else:
            self.filtered_items = self.items[:]
        self.total_count = len(self.items)
        self.done_count = sum(1 for i in self.items if i["done"])

    @event_handler()
    def search(self, value: str = "", **kwargs):
        \"\"\"Filter items by search query.\"\"\"
        self.search_query = value
        self._compute()

    @event_handler()
    def add_item(self, name: str = "", **kwargs):
        \"\"\"Add a new item.\"\"\"
        if name.strip():
            self.items.append({
                "id": self._next_id,
                "name": name.strip(),
                "done": False,
            })
            self._next_id += 1
            self._compute()

    @event_handler()
    def toggle_item(self, item_id: int = 0, **kwargs):
        \"\"\"Toggle item done state.\"\"\"
        for item in self.items:
            if item["id"] == item_id:
                item["done"] = not item["done"]
                break
        self._compute()

    @event_handler()
    def delete_item(self, item_id: int = 0, **kwargs):
        \"\"\"Delete an item.\"\"\"
        self.items = [i for i in self.items if i["id"] != item_id]
        self._compute()

    def get_context_data(self, **kwargs):
        self._compute()
        return {
            "items": self.filtered_items,
            "search_query": self.search_query,
            "total_count": self.total_count,
            "done_count": self.done_count,
            "theme_presets": [
                p for p in self.theme_presets if p["name"] in DEMO_THEME_PRESETS
            ],
            "djust_version": djust.__version__,
%(extra_context)s        }
%(extra_methods)s"""

# ---------------------------------------------------------------------------
# --bare: a placeholder page with one live button and no demo code
# ---------------------------------------------------------------------------

BARE_VIEWS_PY = """\
\"\"\"LiveView for %(app_name)s.\"\"\"

from djust import LiveView
from djust.decorators import event_handler


class %(view_class)s(LiveView):
    template_name = "%(app_name)s/index.html"

    # Nothing user-specific here yet, so the page is public (djust.S005).
    login_required = False

    def mount(self, request, **kwargs):
        self.pings = 0

    @event_handler()
    def ping(self, **kwargs):
        self.pings += 1

    def get_context_data(self, **kwargs):
        return {"pings": self.pings}
"""

BARE_BASE_HTML = """\
{%% load live_tags %%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {# Emits djust's client config; client.js itself is injected automatically. #}
    {%% djust_client_config %%}
    <title>{%% block title %%}%(display_name)s{%% endblock %%}</title>
    <style>
        body { font-family: system-ui, sans-serif; max-width: 40rem; margin: 4rem auto; padding: 0 1.25rem; line-height: 1.55; }
        button { font: inherit; padding: .5rem 1rem; cursor: pointer; }
    </style>
</head>
<body>
    {%% block content %%}{%% endblock %%}
</body>
</html>
"""

BARE_INDEX_HTML = """\
{%% extends "%(app_name)s/base.html" %%}

{%% block content %%}
{%% csrf_token %%}
<div dj-root dj-view="%(app_name)s.views.%(view_class)s">
    <h1>%(display_name)s</h1>
    <p>Your djust project is running. Replace this page in
       <code>%(app_name)s/templates/%(app_name)s/index.html</code> and
       <code>%(app_name)s/views.py</code>.</p>
    <p>
        <button dj-click="ping">Ping the server</button>
        <span>{{ pings }} round trip{{ pings|pluralize }} over the WebSocket</span>
    </p>
    <p><a href="https://docs.djust.org/getting-started/first-liveview/">Your First LiveView</a>
       walks through building a view like this one.</p>
</div>
{%% endblock %%}
"""

# ---------------------------------------------------------------------------
# base.html
# ---------------------------------------------------------------------------

BASE_HTML = """\
{%% load live_tags theme_tags %%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {# djust client bootstrap: emits the API/SSE prefix <meta> tags and the   #}
    {# dj-navigate route map. The djust client.js <script> itself is injected #}
    {# automatically by the LiveView post-processing pipeline, so do NOT add  #}
    {# a manual <script src=".../client.js"> tag (avoids double-load races,   #}
    {# djust.C012). Place this inside <head> BEFORE the client script loads.  #}
    {%% djust_client_config %%}
    {# Theme tokens (CSS variables), the anti-flash script, and theme.js.     #}
    {# Switching a preset or mode pushes new tokens over the WebSocket.       #}
    {%% theme_head %%}
    <title>{%% block title %%}%(display_name)s{%% endblock %%}</title>
    <style>
        /* Every color below is a theme token, so switching presets restyles
           the whole page. Tokens are HSL triplets: hsl(var(--name)). */
        *, *::before, *::after { box-sizing: border-box; }
        body {
            margin: 0;
            font-family: var(--font-sans, system-ui, sans-serif);
            background: hsl(var(--background));
            color: hsl(var(--foreground));
            line-height: 1.55;
            -webkit-font-smoothing: antialiased;
        }
        a { color: hsl(var(--link, var(--primary))); text-decoration: none; }
        a:hover { text-decoration: underline; }
        .wrap { max-width: 64rem; margin: 0 auto; padding: 0 1.25rem; }
        nav {
            border-bottom: 1px solid hsl(var(--border));
            background: hsl(var(--card));
        }
        nav .wrap {
            display: flex; align-items: center; justify-content: space-between;
            gap: 1rem; padding-top: .75rem; padding-bottom: .75rem; flex-wrap: wrap;
        }
        .brand { font-weight: 700; font-size: 1.1rem; }
        .controls { display: flex; align-items: center; gap: .5rem; flex-wrap: wrap; }
        .btn {
            font: inherit; font-size: .9rem; cursor: pointer;
            padding: .45rem .9rem; border-radius: var(--radius, .5rem);
            border: 1px solid hsl(var(--border));
            background: hsl(var(--secondary)); color: hsl(var(--secondary-foreground));
        }
        .btn:hover { filter: brightness(1.05); }
        .btn-primary {
            background: hsl(var(--primary)); color: hsl(var(--primary-foreground));
            border-color: hsl(var(--primary));
        }
        .btn-ghost { background: transparent; border-color: transparent; color: hsl(var(--muted-foreground)); }
        .btn-ghost:hover { color: hsl(var(--destructive)); }
        .btn[disabled] { opacity: .5; cursor: wait; }
        .swatch {
            width: 1.6rem; height: 1.6rem; padding: 0; border-radius: 999px;
            border: 2px solid hsl(var(--border));
        }
        .swatch[aria-pressed="true"] { border-color: hsl(var(--foreground)); box-shadow: 0 0 0 2px hsl(var(--background)) inset; }
        main { padding: 2.5rem 0 4rem; }
        .card {
            background: hsl(var(--card)); color: hsl(var(--card-foreground));
            border: 1px solid hsl(var(--border)); border-radius: var(--radius, .5rem);
            padding: 1.25rem 1.5rem;
        }
        .muted { color: hsl(var(--muted-foreground)); }
        input[type="text"] {
            font: inherit; width: 100%%; padding: .55rem .8rem;
            border-radius: var(--radius, .5rem); border: 1px solid hsl(var(--input));
            background: hsl(var(--background)); color: hsl(var(--foreground));
        }
        input[type="text"]:focus { outline: 2px solid hsl(var(--ring)); outline-offset: 1px; }
        code { font-family: var(--font-mono, ui-monospace, monospace); font-size: .9em;
               background: hsl(var(--muted)); padding: .1em .35em; border-radius: .3em; }
        footer { border-top: 1px solid hsl(var(--border)); padding: 1.25rem 0; font-size: .85rem; }
    </style>
    {%% load static %%}
</head>
<body>
    <nav>
        <div class="wrap">
            <span class="brand">%(display_name)s</span>
            <div class="controls">
%(nav_extra)s\
            </div>
        </div>
    </nav>
    <main class="wrap">
        {%% block content %%}{%% endblock %%}
    </main>
    <footer class="wrap muted">
        djust {{ djust_version }} &middot;
        <a href="https://docs.djust.org/">Documentation</a> &middot;
        <a href="https://github.com/djust-org/djust">GitHub</a>
    </footer>
    {# djust injects the client.js <script> automatically (see <head> note). #}
</body>
</html>
"""

# ---------------------------------------------------------------------------
# index.html — list view template
# ---------------------------------------------------------------------------

INDEX_HTML = """\
{%% extends "%(app_name)s/base.html" %%}

{%% block content %%}
{%% csrf_token %%}
<div dj-root dj-view="%(app_name)s.views.%(view_class)s">

    {# Theme controls live inside dj-root: djust binds dj-* events only here. #}
    <div class="controls" style="justify-content: flex-end; margin-bottom: 1.5rem" aria-label="Theme">
        <span class="muted" style="font-size: .85rem">Theme</span>
        {%% for preset in theme_presets %%}
        <button class="swatch"
                dj-click="set_theme_preset"
                dj-value-preset="{{ preset.name }}"
                title="{{ preset.display_name }}"
                aria-label="Theme: {{ preset.display_name }}"
                aria-pressed="{%% if preset.is_active %%}true{%% else %%}false{%% endif %%}"
                style="background: hsl({{ preset.primary_hsl }})"></button>
        {%% endfor %%}
        <button class="btn" dj-click="toggle_theme_mode" aria-label="Switch between light and dark mode">
            Light / dark
        </button>
    </div>

    <section style="margin-bottom: 2.5rem">
        <h1 style="font-size: 2rem; margin: 0 0 .5rem">Your djust app is running.</h1>
        <p class="muted" style="margin: 0; font-size: 1.05rem">
            This page is one Python class and one template. Every button below is
            handled on the server over a WebSocket, and only the changed parts of
            the page are updated. No JavaScript was written.
        </p>
    </section>

    <section class="card" style="margin-bottom: 2.5rem">
        <div style="display: flex; justify-content: space-between; align-items: baseline; gap: 1rem; flex-wrap: wrap">
            <h2 style="margin: 0; font-size: 1.15rem">Try it: a live list</h2>
            <span class="muted" style="font-size: .9rem">{{ total_count }} items &middot; {{ done_count }} done</span>
        </div>
        <p class="muted" style="margin: .25rem 0 1rem; font-size: .9rem">
            Add an item, tick it off, or search. Then try the theme buttons in the top bar.
        </p>

        <div style="display: grid; grid-template-columns: 1fr auto; gap: .75rem; margin-bottom: 1rem">
            <input type="text"
                   dj-input="search"
                   name="value"
                   value="{{ search_query }}"
                   placeholder="Search items..."
                   aria-label="Search items">
            <form dj-submit="add_item" style="display: flex; gap: .5rem; margin: 0">
                <input type="text" name="name" placeholder="New item..." aria-label="New item name" style="width: 12rem">
                <button type="submit" class="btn btn-primary" dj-loading.disable>Add</button>
            </form>
        </div>

        <ul style="list-style: none; margin: 0; padding: 0; display: grid; gap: .5rem">
            {%% for item in items %%}
            <li style="display: flex; align-items: center; gap: .75rem; padding: .6rem .75rem; border: 1px solid hsl(var(--border)); border-radius: var(--radius, .5rem)">
                <input type="checkbox"
                       dj-click="toggle_item"
                       dj-value-item_id="{{ item.id }}"
                       aria-label="Toggle done"
                       {%% if item.done %%}checked{%% endif %%}>
                <span style="flex: 1; {%% if item.done %%}text-decoration: line-through; opacity: .6{%% endif %%}">{{ item.name }}</span>
                <button class="btn btn-ghost"
                        dj-click="delete_item"
                        dj-value-item_id="{{ item.id }}"
                        dj-confirm="Delete this item?"
                        aria-label="Delete item">Delete</button>
            </li>
            {%% empty %%}
            <li class="muted" style="text-align: center; padding: 2rem 0">
                {%% if search_query %%}No items match "{{ search_query }}".{%% else %%}No items yet. Add one above.{%% endif %%}
            </li>
            {%% endfor %%}
        </ul>
    </section>

    <section style="display: grid; grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr)); gap: 1rem; margin-bottom: 2.5rem">
        <div class="card">
            <h3 style="margin: 0 0 .4rem; font-size: 1rem">The view</h3>
            <p class="muted" style="margin: 0; font-size: .9rem">
                <code>%(app_name)s/views.py</code> holds the state and one method per
                button. Edit it and this page hot-reloads.
            </p>
        </div>
        <div class="card">
            <h3 style="margin: 0 0 .4rem; font-size: 1rem">The template</h3>
            <p class="muted" style="margin: 0; font-size: .9rem">
                <code>%(app_name)s/templates/%(app_name)s/index.html</code> is plain
                Django markup. <code>dj-click</code> names the method to call.
            </p>
        </div>
        <div class="card">
            <h3 style="margin: 0 0 .4rem; font-size: 1rem">The transport</h3>
            <p class="muted" style="margin: 0; font-size: .9rem">
                djust keeps a WebSocket open, diffs the rendered HTML in Rust, and
                patches only what changed. Reconnection is handled for you.
            </p>
        </div>
    </section>

    <section class="card">
        <h2 style="margin: 0 0 .75rem; font-size: 1.15rem">Next steps</h2>
        <ul style="margin: 0; padding-left: 1.2rem; display: grid; gap: .35rem; grid-template-columns: repeat(auto-fit, minmax(20rem, 1fr))">
            <li><a href="https://docs.djust.org/getting-started/first-liveview/">Your First LiveView</a><span class="muted">&nbsp;— build a counter from scratch</span></li>
            <li><a href="https://docs.djust.org/theming/overview/">Theming</a><span class="muted">&nbsp;— the presets and modes used on this page</span></li>
            <li><a href="https://docs.djust.org/forms/">Forms</a><span class="muted">&nbsp;— real-time validation with Django forms</span></li>
            <li><a href="https://docs.djust.org/guides/components/">Components</a><span class="muted">&nbsp;— reusable live components</span></li>
            <li><a href="https://docs.djust.org/guides/deployment/">Deployment</a><span class="muted">&nbsp;— static files, hosts, and servers</span></li>
            <li><a href="https://github.com/djust-org/djust">GitHub</a><span class="muted">&nbsp;— source, issues, and releases</span></li>
        </ul>
    </section>

%(template_extra)s\
</div>
{%% endblock %%}
"""

# ---------------------------------------------------------------------------
# Makefile
# ---------------------------------------------------------------------------

MAKEFILE = """\
.PHONY: dev test migrate check install collectstatic

# The project's own environment, so no activation is needed. An exported
# PYTHON variable does not override this; `make dev PYTHON=python` does.
PYTHON = .venv/bin/python

dev:
\t$(PYTHON) -m uvicorn %(app_name)s.asgi:application --host 127.0.0.1 --port 8000 --reload

test:
\t$(PYTHON) manage.py test

migrate:
\t$(PYTHON) manage.py migrate

check:
\t$(PYTHON) manage.py djust_check

install:
\tuv pip install --python .venv -r requirements.txt

collectstatic:
\t$(PYTHON) manage.py collectstatic --noinput
"""

# ---------------------------------------------------------------------------
# requirements.txt
# ---------------------------------------------------------------------------

REQUIREMENTS_TXT = """\
django>=5.1
%(djust_requirement)s
channels>=4.0
uvicorn[standard]>=0.30
"""

# ---------------------------------------------------------------------------
# .gitignore
# ---------------------------------------------------------------------------

GITIGNORE = """\
__pycache__/
*.py[cod]
*.so
.venv/
venv/
db.sqlite3
db.sqlite3-journal
staticfiles/
*.egg-info/
dist/
build/
.eggs/
.env
*.log
.DS_Store
"""

# ---------------------------------------------------------------------------
# .env.example — committed template for developer environment variables
# ---------------------------------------------------------------------------
#
# Scaffolded projects default ``DEBUG=False`` and narrow ``ALLOWED_HOSTS``
# in settings.py so unconfigured production deployments fail safe. Local
# development picks the values up from ``.env`` via python-dotenv or
# whatever process runner the developer uses. This template is written to
# disk as ``.env.example`` — the developer copies it to ``.env`` once.

ENV_EXAMPLE = """\
# %(display_name)s — local development environment variables.
#
# Copy this file to ``.env`` for local development:
#
#     cp .env.example .env
#
# ``.env`` is listed in ``.gitignore`` — never commit real secrets.
# Production deployments should set these via the hosting platform
# (systemd unit, Docker env, Fly.io secrets, Heroku config vars, etc.)
# rather than shipping a ``.env`` file.

# Enable Django debug mode and verbose error pages. Must be False in
# production — the scaffolded settings.py defaults to False when unset.
DEBUG=True

# Django secret key. The scaffolded settings.py falls back to an
# ``django-insecure-<random>`` default for local bootstrap, but you
# should set a real one here (and a different one in production).
SECRET_KEY=%(secret_key)s

# Comma-separated list of hostnames Django will accept. The scaffolded
# settings.py defaults to ``localhost,127.0.0.1`` when unset.
ALLOWED_HOSTS=localhost,127.0.0.1
"""

# ---------------------------------------------------------------------------
# Feature: --with-auth — login template
# ---------------------------------------------------------------------------

LOGIN_HTML = """\
{%% extends "%(app_name)s/base.html" %%}

{%% block title %%}Login - %(display_name)s{%% endblock %%}

{%% block content %%}
<div class="max-w-md mx-auto mt-16">
    <div class="glass rounded-xl p-8">
        <h2 class="text-2xl font-bold text-white mb-6 text-center">Sign In</h2>
        <form method="post" action="{%% url 'login' %%}">
            {%% csrf_token %%}
            <input type="hidden" name="next" value="{{ next }}">
            {%% if form.errors %%}
            <div class="mb-4 p-3 rounded-lg bg-red-500/10 border border-red-500/30 text-red-400 text-sm">
                Invalid username or password.
            </div>
            {%% endif %%}
            <div class="mb-4">
                <label class="block text-sm text-gray-400 mb-1">Username</label>
                <input type="text" name="username" autofocus
                       class="w-full px-4 py-2 rounded-lg bg-surface-800 border border-white/10 text-gray-200 focus:outline-none focus:border-indigo-500">
            </div>
            <div class="mb-6">
                <label class="block text-sm text-gray-400 mb-1">Password</label>
                <input type="password" name="password"
                       class="w-full px-4 py-2 rounded-lg bg-surface-800 border border-white/10 text-gray-200 focus:outline-none focus:border-indigo-500">
            </div>
            <button type="submit"
                    class="w-full py-2 rounded-lg bg-indigo-600 text-white hover:bg-indigo-500 transition font-medium">
                Sign In
            </button>
        </form>
    </div>
</div>
{%% endblock %%}
"""

# ---------------------------------------------------------------------------
# Feature: --with-auth — extra settings
# ---------------------------------------------------------------------------

AUTH_SETTINGS_EXTRA = """
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
"""

# ---------------------------------------------------------------------------
# Feature: --with-auth — extra urls
# ---------------------------------------------------------------------------

AUTH_URLS_EXTRA = """
# Auth URLs
from django.contrib.auth import views as auth_views

urlpatterns += [
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="%(app_name)s/login.html",
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]
"""

# ---------------------------------------------------------------------------
# Feature: --with-auth — nav extra (username + logout link)
# ---------------------------------------------------------------------------

AUTH_NAV_EXTRA = """\
            <div class="flex items-center gap-3">
                {%% if user.is_authenticated %%}
                <span class="text-sm text-gray-400">{{ user.username }}</span>
                <a href="{%% url 'logout' %%}" class="text-sm text-indigo-400 hover:text-indigo-300">Logout</a>
                {%% else %%}
                <a href="{%% url 'login' %%}" class="text-sm text-indigo-400 hover:text-indigo-300">Login</a>
                {%% endif %%}
            </div>
"""

# ---------------------------------------------------------------------------
# Feature: --with-db — models.py
# ---------------------------------------------------------------------------

MODELS_PY = """\
\"\"\"Models for %(app_name)s.\"\"\"

from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=200)
    done = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.name
"""

# ---------------------------------------------------------------------------
# Feature: --with-db — admin.py
# ---------------------------------------------------------------------------

ADMIN_PY = """\
from django.contrib import admin

from .models import Item


@admin.register(Item)
class ItemAdmin(admin.ModelAdmin):
    list_display = ["name", "done", "created_at"]
    list_filter = ["done"]
    search_fields = ["name"]
"""

# ---------------------------------------------------------------------------
# Feature: --with-db — views.py overrides (DB-backed items)
# ---------------------------------------------------------------------------

DB_VIEWS_EXTRA_IMPORTS = """\
from .models import Item
"""

DB_VIEWS_MOUNT_OVERRIDE = """\
        self.search_query = ""
"""

DB_VIEWS_COMPUTE_OVERRIDE = """\
    def _compute(self):
        \"\"\"Recompute filtered items from database.\"\"\"
        qs = Item.objects.all()
        if self.search_query:
            qs = qs.filter(name__icontains=self.search_query)
        self.items = [
            {"id": i.pk, "name": i.name, "done": i.done}
            for i in qs
        ]
        self.total_count = Item.objects.count()
        self.done_count = Item.objects.filter(done=True).count()
"""

DB_VIEWS_ADD_ITEM_OVERRIDE = """\
    @event_handler()
    def add_item(self, name: str = "", **kwargs):
        \"\"\"Add a new item to the database.\"\"\"
        if name.strip():
            Item.objects.create(name=name.strip())
            self._compute()
"""

DB_VIEWS_TOGGLE_OVERRIDE = """\
    @event_handler()
    def toggle_item(self, item_id: int = 0, **kwargs):
        \"\"\"Toggle item done state in database.\"\"\"
        try:
            item = Item.objects.get(pk=item_id)
            item.done = not item.done
            item.save(update_fields=["done"])
        except Item.DoesNotExist:
            pass
        self._compute()
"""

DB_VIEWS_DELETE_OVERRIDE = """\
    @event_handler()
    def delete_item(self, item_id: int = 0, **kwargs):
        \"\"\"Delete an item from the database.\"\"\"
        Item.objects.filter(pk=item_id).delete()
        self._compute()
"""

# ---------------------------------------------------------------------------
# Feature: --with-presence — template partial
# ---------------------------------------------------------------------------

PRESENCE_TEMPLATE_EXTRA = """\

    <!-- Presence indicators -->
    <div class="mt-8 border-t border-white/5 pt-4">
        <div class="flex items-center gap-2 text-sm text-gray-400">
            <span class="w-2 h-2 rounded-full bg-emerald-400"></span>
            {{ presence_count }} user{{ presence_count|pluralize }} online
        </div>
        <div class="flex gap-1 mt-2">
            {%% for user in presence_list %%}
            <div class="w-8 h-8 rounded-full bg-indigo-600 flex items-center justify-center text-xs text-white"
                 title="{{ user.username }}">
                {{ user.username|first|upper }}
            </div>
            {%% endfor %%}
        </div>
    </div>
"""

# ---------------------------------------------------------------------------
# Feature: --with-streaming — template partial
# ---------------------------------------------------------------------------

STREAMING_TEMPLATE_EXTRA = """\

    <!-- Stream output -->
    <div class="mt-8 border-t border-white/5 pt-4">
        <h3 class="text-sm font-medium text-gray-400 mb-2">Live Feed</h3>
        <div dj-stream="feed" dj-stream-mode="append"
             class="glass rounded-lg p-4 max-h-64 overflow-y-auto space-y-1 text-sm font-mono">
            {%% for entry in streams.feed %%}
            <div class="text-gray-300">{{ entry }}</div>
            {%% endfor %%}
        </div>
    </div>
"""

# ---------------------------------------------------------------------------
# Feature: --from-schema — views.py for schema-generated app
# ---------------------------------------------------------------------------

SCHEMA_VIEWS_PY = """\
\"\"\"LiveViews for %(app_name)s — generated from schema.\"\"\"

from djust import LiveView
from djust.decorators import event_handler
%(schema_model_imports)s


%(schema_view_classes)s"""

SCHEMA_VIEW_CLASS = """\
class %(view_class)s(LiveView):
    template_name = "%(app_name)s/%(template_name)s"

    def mount(self, request, **kwargs):
%(mount_body)s
        self._compute()

    def _compute(self):
        \"\"\"Recompute from database.\"\"\"
%(compute_body)s

%(handler_methods)s
    def get_context_data(self, **kwargs):
        self._compute()
        return {
%(context_body)s        }
"""

SCHEMA_MODELS_PY = """\
\"\"\"Models for %(app_name)s — generated from schema.\"\"\"

from django.db import models

%(model_classes)s"""

SCHEMA_MODEL_CLASS = """\

class %(model_name)s(models.Model):
%(field_definitions)s
    class Meta:
        ordering = ["-pk"]

    def __str__(self):
        return %(str_field)s
"""

SCHEMA_ADMIN_PY = """\
from django.contrib import admin

%(admin_imports)s

%(admin_registrations)s"""

SCHEMA_LIST_HTML = """\
{%% extends "%(app_name)s/base.html" %%}

{%% block title %%}%(model_display)s - %(display_name)s{%% endblock %%}

{%% block content %%}
{%% csrf_token %%}
<div dj-root dj-view="%(app_name)s.views.%(view_class)s">

    <h1 class="text-2xl font-bold text-white mb-6">%(model_display)s</h1>

    <!-- Search -->
    <div class="mb-6">
        <input type="text"
               dj-input="search"
               name="value"
               value="{{ search_query }}"
               placeholder="Search %(model_display_lower)s..."
               class="w-full px-4 py-2 rounded-lg bg-surface-800 border border-white/10 text-gray-200 placeholder-gray-500 focus:outline-none focus:border-indigo-500">
    </div>

    <!-- Add form -->
    <form dj-submit="create" class="glass rounded-lg p-4 mb-6 grid grid-cols-1 sm:grid-cols-2 gap-3">
%(form_fields_html)s\
        <div class="sm:col-span-2">
            <button type="submit"
                    class="px-4 py-2 rounded-lg bg-indigo-600 text-white hover:bg-indigo-500 transition"
                    dj-loading.class="opacity-50" dj-loading.disable>
                Add %(model_display_singular)s
            </button>
        </div>
    </form>

    <!-- List -->
    <div class="space-y-2">
        {%% for item in items %%}
        <div class="glass rounded-lg px-4 py-3 flex items-center justify-between group">
            <div class="flex items-center gap-4">
%(list_item_fields)s\
            </div>
            <button dj-click="delete"
                    data-item_id:int="{{ item.id }}"
                    dj-confirm="Delete this %(model_display_singular_lower)s?"
                    class="text-red-400 opacity-0 group-hover:opacity-100 hover:text-red-300 transition text-sm">
                Delete
            </button>
        </div>
        {%% empty %%}
        <div class="text-center text-gray-500 py-12">No %(model_display_lower)s yet.</div>
        {%% endfor %%}
    </div>

</div>
{%% endblock %%}
"""


# Keep this an entry point, not a second copy of the framework conventions.
AGENTS_MD = """# djust application guidance

Before changing live views, forms, templates or navigation, read:
- [Application engineering conventions](https://github.com/djust-org/djust/blob/main/docs/ai/conventions.md)
- [Focused AI reference](https://github.com/djust-org/djust/tree/main/docs/ai)

Use the documentation/source matching the installed djust release; main may
contain newer APIs. Prefer native Django/djust behavior and declarative options
before application wrappers. Keep project-specific instructions in this file.
"""
