# Kubernetes secrets for Django Rust Live
apiVersion: v1
kind: Secret
metadata:
  name: django-rust-secret
  namespace: django-rust
type: Opaque
stringData:
  secret-key: "jw1k2$4zpas54@^@3+8nutp^s&=5ouq!jl-f9zrh!q$d2uh^&v"
