/**
 * Empirical reproduction: replay REAL NYC Claims ClaimDetailView patches
 * through the actual client.js and check for drift.
 *
 * Fixture generated by running:
 *   cd nyc-claims
 *   .venv/bin/python scratch_capture_tab_patches.py > tests/js/fixtures/nyc_claims_real_patches.json
 *
 * The fixture captures the raw patches that handle_url_change WOULD send if
 * the workaround in websocket.py (structural_ops > 5 → full HTML) were
 * bypassed. Each render records the tab name, version, expected HTML, and
 * the patch list.
 *
 * If the PR #642 drift is caused by the patches themselves (as opposed to
 * something in the browser environment JSDOM doesn't model), this test
 * will catch it.
 */

import { describe, it, expect } from 'vitest';
import { JSDOM } from 'jsdom';
import fs from 'fs';

const fixture = JSON.parse(
    fs.readFileSync('./tests/js/fixtures/nyc_claims_real_patches.json', 'utf-8')
);

const clientCode = fs.readFileSync(
    './python/djust/static/djust/client.js',
    'utf-8'
);

function createDom(initialHtml) {
    const dom = new JSDOM(
        `<!DOCTYPE html><html><body>${initialHtml}</body></html>`,
        { runScripts: 'dangerously' }
    );
    const { window } = dom;

    if (!window.CSS) window.CSS = {};
    if (!window.CSS.escape) {
        window.CSS.escape = (s) => String(s).replace(/([^\w-])/g, '\\$1');
    }

    // Capture warnings/errors so we can see patch failures
    const logs = [];
    window.console = {
        log: (...args) => logs.push(['log', args.join(' ')]),
        error: (...args) => logs.push(['error', args.join(' ')]),
        warn: (...args) => logs.push(['warn', args.join(' ')]),
        debug: () => {},
        info: () => {},
    };

    window.eval(clientCode);
    window.djust._applyPatches = window.djust.applyPatches;
    return { dom, window, logs };
}

function collectDjIds(root) {
    const ids = [];
    const walk = (node) => {
        if (node.nodeType === 1) {
            const id = node.getAttribute && node.getAttribute('dj-id');
            if (id) ids.push(id);
            for (const child of node.children) walk(child);
        }
    };
    walk(root);
    return ids;
}

function collectDjIdsFromHtml(window, html) {
    const tmp = window.document.createElement('div');
    tmp.innerHTML = html;
    return collectDjIds(tmp);
}

describe('Real NYC Claims ClaimDetailView patch replay', () => {
    it('replays 6-render tab-switch sequence from real view code', async () => {
        const renders = fixture.renders;
        expect(renders.length).toBe(6);

        // R1 baseline
        const initial = renders[0];
        const { window, logs } = createDom(initial.html);
        const { document } = window;

        const root = document.querySelector('[dj-root]');
        expect(root).toBeTruthy();

        const driftReport = [];

        for (let i = 1; i < renders.length; i++) {
            const r = renders[i];
            const prevTab = renders[i - 1].tab;

            const ok = await window.djust._applyPatches(r.patches);

            // Extract the [dj-root] subtree of the current DOM
            const currentRoot = document.querySelector('[dj-root]');
            const actualIds = collectDjIds(currentRoot);
            const expectedIds = collectDjIdsFromHtml(window, r.html);

            // Check which IDs exist in actual DOM but are missing from expected
            // (indicates stale nodes that should have been removed)
            const staleInActual = actualIds.filter(id => !expectedIds.includes(id));
            // Check which IDs are expected but missing from actual
            // (indicates new nodes that should have been inserted but weren't)
            const missingInActual = expectedIds.filter(id => !actualIds.includes(id));

            const drift = {
                step: i,
                from: prevTab,
                to: r.tab,
                patches: r.patches.length,
                applyOk: ok,
                expectedCount: expectedIds.length,
                actualCount: actualIds.length,
                staleInActual: staleInActual.slice(0, 10),
                missingInActual: missingInActual.slice(0, 10),
                idsMatch: staleInActual.length === 0 && missingInActual.length === 0,
            };
            driftReport.push(drift);
        }

        // Log every step for visibility (console.error so it shows in test output)
        for (const d of driftReport) {
            const status = d.idsMatch ? 'OK' : 'DRIFT';
            console.error(
                `[step ${d.step}] ${d.from} → ${d.to}: ${d.patches} patches, ` +
                `applyOk=${d.applyOk}, dom=${d.actualCount} expected=${d.expectedCount} → ${status}`
            );
            if (!d.idsMatch) {
                if (d.staleInActual.length)
                    console.error(`  stale in actual: ${d.staleInActual.join(',')}`);
                if (d.missingInActual.length)
                    console.error(`  missing in actual: ${d.missingInActual.join(',')}`);
            }
        }

        // Show any warn/error console messages from the patcher
        const issues = logs.filter(([lvl]) => lvl === 'warn' || lvl === 'error');
        if (issues.length) {
            console.error('--- Client-side warn/error during patching ---');
            for (const [lvl, msg] of issues.slice(0, 20)) {
                console.error(`  [${lvl}] ${msg}`);
            }
        }

        // The critical assertion: no drift at any step
        const drifted = driftReport.filter(d => !d.idsMatch);
        expect(drifted.map(d => ({ step: d.step, from: d.from, to: d.to }))).toEqual([]);
    });
});
