"""Documented WCAG AA contrast exemptions for built-in theme presets.

``python/djust/tests/test_theming_contrast_all_presets_2060.py`` gates every
registered preset in ``djust.theming.presets.THEME_PRESETS`` against the same
6-pair x 2-mode WCAG AA matrix that
``test_theming_new_themes_v11.py::TestContrast`` already gates strictly for
the 5 newest themes (sakura, obsidian, dune, mission_control, art_nouveau —
no exemptions permitted there, by design).

Scope discipline (#1079): this module does NOT redesign any shipped legacy
palette. Every (preset, mode, fg_token, bg_token) pair that failed AA when
the all-presets gate was introduced is listed here as a documented,
reason-carrying exemption rather than silently left ungated or force-fixed.
Fixing these palettes is out of scope for #2060; see the PR body for the
catastrophic-ratio (<3.0) candidates flagged as a follow-up.

Entries were auto-generated from
``scripts/report_theme_contrast.py --python-dict`` (2026-07, #2060) — do
not hand-edit ratios; regenerate the affected entry by re-running the report
if a palette changes.

**Load-bearing invariant (#1859):** every entry here must still be NEEDED.
``test_theming_contrast_all_presets_2060.py`` asserts that any exemption
whose pair now (post-palette-edit) meets its WCAG minimum is a "stale
exemption" and fails the suite until the entry is removed. This keeps the
list from silently drifting into false protection — an exemption for a pair
that already passes is decorative, not documentation.

To grandfather a NEW deliberate exception (e.g. a newly authored legacy-
matching palette), add an entry here with a specific reason (not the
generic "grandfathered..." string used for the bulk 2026-07 import) citing
why the ratio is acceptable (brand identity, large-text-only usage, etc.)
and the tracking issue.
"""

from __future__ import annotations

# Keyed by (preset_name, mode, foreground_token, background_token) ->
# human-readable reason. Mirrors the PAIRS list in
# test_theming_new_themes_v11.py::TestContrast and
# test_theming_contrast_all_presets_2060.py.
A11Y_EXEMPTIONS: dict[tuple[str, str, str, str], str] = {
    (
        "adaptive",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.39",
    (
        "adaptive",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.29",
    (
        "amber",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "amber",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.39",
    (
        "amber",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "aurora",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.59",
    (
        "aurora",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.37",
    (
        "aurora",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.32",
    (
        "aurora",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.37",
    (
        "aurora",
        "dark",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.52",
    (
        "ayu",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.24",
    (
        "ayu",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.64",
    (
        "ayu",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.18",
    (
        "ayu",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.64",
    (
        "ayu",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.70",
    (
        "blue",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.62",
    (
        "candy",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.56",
    (
        "candy",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.39",
    (
        "candy",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.11",
    (
        "candy",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.82",
    (
        "catppuccin",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.09",
    (
        "catppuccin",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.30",
    (
        "catppuccin",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 1.77",
    (
        "catppuccin",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.09",
    (
        "catppuccin",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.30",
    (
        "cyberdeck",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.85",
    (
        "cyberdeck",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.29",
    (
        "cyberdeck",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.30",
    (
        "cyberdeck",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.00",
    (
        "cyberdeck",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.43",
    (
        "cyberpunk",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "cyberpunk",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.77",
    (
        "cyberpunk",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "cyberpunk",
        "dark",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.77",
    (
        "dashboard",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.02",
    (
        "dashboard",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.42",
    (
        "default",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.62",
    (
        "djust",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.78",
    (
        "djust",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.69",
    (
        "djust",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.87",
    (
        "djust",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.66",
    (
        "djust",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.69",
    (
        "djust",
        "dark",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.53",
    (
        "docs",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.89",
    (
        "docs",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.89",
    (
        "docs",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.26",
    (
        "docs",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.30",
    (
        "dracula",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.00",
    (
        "dracula",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.48",
    (
        "dracula",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.92",
    (
        "dracula",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.02",
    (
        "ember",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.11",
    (
        "ember",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.46",
    (
        "ember",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.37",
    (
        "everforest",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.73",
    (
        "everforest",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.06",
    (
        "everforest",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.57",
    (
        "forest",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.30",
    (
        "forest",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "forest",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.19",
    (
        "forest",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.30",
    (
        "forest",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "forest_floor",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.44",
    (
        "forest_floor",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.49",
    (
        "github",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.65",
    (
        "github",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.35",
    (
        "green",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.20",
    (
        "green",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.62",
    (
        "gruvbox",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.51",
    (
        "gruvbox",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.49",
    (
        "gruvbox",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.38",
    (
        "gruvbox",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.38",
    (
        "gruvbox",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.49",
    (
        "gruvbox",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.45",
    (
        "handcraft",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.96",
    (
        "handcraft",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.87",
    (
        "handcraft",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.36",
    (
        "handcraft",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.46",
    (
        "ink",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.80",
    (
        "kanagawa",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.76",
    (
        "kanagawa",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.97",
    (
        "linear",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.37",
    (
        "linear",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.37",
    (
        "linear",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.67",
    (
        "linear",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.82",
    (
        "magazine",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.50",
    (
        "magazine",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.50",
    (
        "magazine",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.19",
    (
        "magazine",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.19",
    (
        "medical",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.04",
    (
        "medical",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.52",
    (
        "medical",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.46",
    (
        "midnight",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.04",
    (
        "midnight",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.32",
    (
        "monokai",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.80",
    (
        "monokai",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.80",
    (
        "monokai",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.80",
    (
        "monokai",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.80",
    (
        "monokai",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.95",
    (
        "natural20",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.63",
    (
        "natural20",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "natural20",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.44",
    (
        "natural20",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.63",
    (
        "natural20",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.36",
    (
        "nebula",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.41",
    (
        "nebula",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "nebula",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.41",
    (
        "nebula",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "neon_noir",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.40",
    (
        "neon_noir",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.19",
    (
        "neon_noir",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.19",
    (
        "neon_noir",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.22",
    (
        "nord",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.02",
    (
        "nord",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.14",
    (
        "nord",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.22",
    (
        "nord",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.02",
    (
        "nord",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.14",
    (
        "nord",
        "dark",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.15",
    (
        "nord",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.35",
    (
        "notion",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.92",
    (
        "notion",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.34",
    (
        "notion",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.18",
    (
        "notion",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.39",
    (
        "ocean_deep",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.51",
    (
        "ocean_deep",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.39",
    (
        "ocean_deep",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.74",
    (
        "ocean_deep",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.39",
    (
        "one_dark",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.36",
    (
        "one_dark",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.20",
    (
        "one_dark",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.20",
    (
        "one_dark",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.70",
    (
        "orange",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.74",
    (
        "orange",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.62",
    (
        "outrun",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.61",
    (
        "outrun",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "outrun",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.08",
    (
        "outrun",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.61",
    (
        "outrun",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "outrun",
        "dark",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.08",
    (
        "paper",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.47",
    (
        "paper",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.16",
    (
        "poimandres",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 1.74",
    (
        "poimandres",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.44",
    (
        "poimandres",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.21",
    (
        "purple",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.62",
    (
        "purple",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.44",
    (
        "raycast",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.26",
    (
        "retro_computing",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.49",
    (
        "rose",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.36",
    (
        "rose",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.62",
    (
        "rose",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.48",
    (
        "rose_pine",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.91",
    (
        "rose_pine",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.91",
    (
        "rose_pine",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 1.65",
    (
        "rose_pine",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.91",
    (
        "rose_pine",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.91",
    (
        "shadcn",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.62",
    (
        "slate",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "slate",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "solarized",
        "light",
        "card_foreground",
        "card",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.36",
    (
        "solarized",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.30",
    (
        "solarized",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.90",
    (
        "solarized",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.98",
    (
        "solarized",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.30",
    (
        "solarized",
        "dark",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.90",
    (
        "solarpunk",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.84",
    (
        "solarpunk",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.42",
    (
        "stripe",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.39",
    (
        "stripe",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.22",
    (
        "sunrise",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.18",
    (
        "sunrise",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.76",
    (
        "sunrise",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.39",
    (
        "supabase",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 1.99",
    (
        "supabase",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.39",
    (
        "supabase",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.39",
    (
        "swiss",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.88",
    (
        "swiss",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.88",
    (
        "synthwave",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.34",
    (
        "synthwave",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "synthwave",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.34",
    (
        "synthwave",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "tailwind",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.86",
    (
        "tailwind",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "tailwind",
        "light",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.45",
    (
        "tailwind",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.86",
    (
        "tailwind",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.78",
    (
        "terminal",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.42",
    (
        "terminal",
        "dark",
        "muted_foreground",
        "background",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.14",
    (
        "tokyo_night",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.38",
    (
        "tokyo_night",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.64",
    (
        "tokyo_night",
        "light",
        "accent_foreground",
        "accent",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 1.91",
    (
        "tokyo_night",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.38",
    (
        "tokyo_night",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 2.64",
    (
        "vercel",
        "light",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.44",
    (
        "vercel",
        "light",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.46",
    (
        "vercel",
        "dark",
        "primary_foreground",
        "primary",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 4.44",
    (
        "vercel",
        "dark",
        "destructive_foreground",
        "destructive",
    ): "grandfathered at gate introduction (2026-07, #2060); ratio 3.96",
}


def get_exemption_reason(preset: str, mode: str, fg_token: str, bg_token: str) -> str | None:
    """Return the documented exemption reason for this pair, or ``None`` if not exempt."""
    return A11Y_EXEMPTIONS.get((preset, mode, fg_token, bg_token))
