"""
Tests for CLI startproject/startapp commands (#266).
"""

import types

import pytest

from djust.cli import cmd_startproject, cmd_startapp


@pytest.fixture
def tmp_cwd(tmp_path, monkeypatch):
    """Switch cwd to a temp directory for scaffold tests."""
    monkeypatch.chdir(tmp_path)
    return tmp_path


class TestStartProjectDeprecated:
    """``djust startproject`` is deprecated (#1791) and now delegates to the
    canonical ``djust new`` generator (``djust.scaffolding.generator``) instead
    of emitting its own divergent — and broken (#1787) — project templates.

    These tests pin the *deprecation + delegation* contract:

    - it prints a deprecation notice pointing at ``djust new``;
    - the produced project is the same warning-clean, uvicorn-booting output
      ``djust new`` produces — NOT the old ``daphne`` / ``live_session()``
      project (which did not boot);
    - validation (invalid name, existing directory) still exits non-zero.

    Auto-setup is disabled (``no_setup=True``) so the tests don't shell out to
    venv/install/migrate.
    """

    def _args(self, name):
        return types.SimpleNamespace(name=name, no_setup=True)

    def test_prints_deprecation_notice(self, tmp_cwd, capsys):
        cmd_startproject(self._args("mysite"))
        out = capsys.readouterr().out
        assert "deprecated" in out.lower()
        assert "djust new" in out

    def test_creates_project_directory(self, tmp_cwd):
        cmd_startproject(self._args("mysite"))
        assert (tmp_cwd / "mysite").is_dir()

    def test_creates_manage_py(self, tmp_cwd):
        cmd_startproject(self._args("mysite"))
        manage = tmp_cwd / "mysite" / "manage.py"
        assert manage.exists()
        assert "mysite.settings" in manage.read_text()

    def test_delegates_to_canonical_generator_not_old_templates(self, tmp_cwd):
        """The produced project must be the NEW (warning-clean, booting) shape,
        not the deprecated startproject boilerplate."""
        cmd_startproject(self._args("mysite"))
        settings = (tmp_cwd / "mysite" / "mysite" / "settings.py").read_text()
        # New stack uses channels, not the dropped daphne app.
        assert '"channels"' in settings
        assert '"daphne"' not in settings
        assert '"djust"' in settings
        assert "whitenoise" not in settings
        assert "LIVEVIEW_ALLOWED_MODULES" in settings
        # Generated by the canonical `djust new` generator.
        assert "python -m djust new" in settings

    def test_asgi_is_protocol_type_router_not_live_session(self, tmp_cwd):
        """The #1787 regression guard: asgi.py must be a real ASGI app, not the
        broken ``application = live_session()`` shape."""
        cmd_startproject(self._args("mysite"))
        asgi = (tmp_cwd / "mysite" / "mysite" / "asgi.py").read_text()
        assert "application = live_session()" not in asgi
        assert "ProtocolTypeRouter" in asgi
        assert "ASGIStaticFilesHandler" in asgi

    def test_creates_templates_directory(self, tmp_cwd):
        cmd_startproject(self._args("mysite"))
        assert (tmp_cwd / "mysite" / "templates").is_dir()

    def test_rejects_existing_directory(self, tmp_cwd):
        (tmp_cwd / "existing").mkdir()
        with pytest.raises(SystemExit):
            cmd_startproject(self._args("existing"))

    def test_rejects_invalid_name(self, tmp_cwd):
        with pytest.raises(SystemExit):
            cmd_startproject(self._args("my-site"))

    def test_settings_defaults_debug_to_false_from_env(self, tmp_cwd):
        """#637 (still upheld via the canonical generator): scaffolded
        settings.py must fail safe — unconfigured deploys default to
        DEBUG=False, not DEBUG=True."""
        cmd_startproject(self._args("mysite"))
        settings = (tmp_cwd / "mysite" / "mysite" / "settings.py").read_text()
        assert "DEBUG = True" not in settings
        assert 'DEBUG = os.environ.get("DEBUG", "False")' in settings
        assert '.lower() in ("true", "1", "yes")' in settings

    def test_settings_narrows_allowed_hosts_from_env(self, tmp_cwd):
        """#637: ALLOWED_HOSTS defaults to localhost only when env var unset."""
        cmd_startproject(self._args("mysite"))
        settings = (tmp_cwd / "mysite" / "mysite" / "settings.py").read_text()
        assert 'ALLOWED_HOSTS = ["*"]' not in settings
        assert 'os.environ.get("ALLOWED_HOSTS"' in settings
        assert '"localhost,127.0.0.1"' in settings

    def test_generates_env_example_file(self, tmp_cwd):
        """#637: the project ships a ``.env.example`` developers copy to
        ``.env`` for local development."""
        cmd_startproject(self._args("mysite"))
        env_example = tmp_cwd / "mysite" / ".env.example"
        assert env_example.exists()
        content = env_example.read_text()
        assert "cp .env.example .env" in content
        assert "DEBUG=True" in content
        assert "SECRET_KEY=" in content
        assert "ALLOWED_HOSTS=localhost,127.0.0.1" in content
        for line in content.splitlines():
            if line.startswith("SECRET_KEY="):
                value = line.split("=", 1)[1]
                assert len(value) >= 20, "secret key should be a real token"
                assert "%(secret_key)s" not in value

    def test_env_example_not_in_gitignore_but_dot_env_is(self, tmp_cwd):
        """``.env.example`` is committed, ``.env`` is ignored."""
        cmd_startproject(self._args("mysite"))
        gitignore = (tmp_cwd / "mysite" / ".gitignore").read_text()
        lines = {line.strip() for line in gitignore.splitlines()}
        assert ".env" in lines
        assert ".env.example" not in lines


class TestStartApp:
    def test_creates_app_directory(self, tmp_cwd):
        args = types.SimpleNamespace(name="dashboard")
        cmd_startapp(args)
        assert (tmp_cwd / "dashboard").is_dir()

    def test_creates_views_with_liveview(self, tmp_cwd):
        args = types.SimpleNamespace(name="dashboard")
        cmd_startapp(args)
        views = tmp_cwd / "dashboard" / "views.py"
        assert views.exists()
        content = views.read_text()
        assert "class DashboardView(LiveView)" in content
        assert "@event_handler()" in content

    def test_creates_template_with_djust_view(self, tmp_cwd):
        args = types.SimpleNamespace(name="dashboard")
        cmd_startapp(args)
        template = tmp_cwd / "dashboard" / "templates" / "dashboard" / "index.html"
        assert template.exists()
        content = template.read_text()
        assert 'dj-view="dashboard.views.DashboardView"' in content

    def test_creates_urls(self, tmp_cwd):
        args = types.SimpleNamespace(name="dashboard")
        cmd_startapp(args)
        urls = tmp_cwd / "dashboard" / "urls.py"
        assert urls.exists()
        content = urls.read_text()
        assert "DashboardView" in content

    def test_creates_apps_py(self, tmp_cwd):
        args = types.SimpleNamespace(name="dashboard")
        cmd_startapp(args)
        apps = tmp_cwd / "dashboard" / "apps.py"
        assert apps.exists()
        content = apps.read_text()
        assert "class DashboardConfig(AppConfig)" in content
        assert 'name = "dashboard"' in content

    def test_creates_models_py(self, tmp_cwd):
        args = types.SimpleNamespace(name="dashboard")
        cmd_startapp(args)
        models = tmp_cwd / "dashboard" / "models.py"
        assert models.exists()

    def test_rejects_existing_directory(self, tmp_cwd):
        (tmp_cwd / "existing").mkdir()
        args = types.SimpleNamespace(name="existing")
        with pytest.raises(SystemExit):
            cmd_startapp(args)

    def test_underscore_name_generates_camelcase_class(self, tmp_cwd):
        args = types.SimpleNamespace(name="user_profile")
        cmd_startapp(args)
        views = tmp_cwd / "user_profile" / "views.py"
        content = views.read_text()
        assert "class UserProfileView(LiveView)" in content
